### ISSUE TITLE
AttributeError: module 'paperscraper' has no attribute 'search_papers'

### ISSUE THREAD

**Issue by combspk** [NCBI-Codeathons/mlxai-2024-team-saddler#22]
What version of paperscraper are you using? I am using version 0.2.11 for Python 3.11.8 and am getting the following error:

Search: "Aspirin mechanism of action scholarly articles"
Traceback (most recent call last):
  File "C:\Users\combspk\Desktop\codeathon\mlxai-2024-team-saddler\app\llm-test.py", line 8, in <module>
    chem_res = tpa.run("What is the molecular weight of aspirin and its action mechanism?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\Desktop\codeathon\mlxai-2024-team-saddler\app\agents\toxpipe.py", line 82, in run
    outputs = self.agent_executor_chem({"input": prompt})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\chains\base.py", line 378, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\chains\base.py", line 163, in invoke
    raise e
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\agents\agent.py", line 1391, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\agents\agent.py", line 1097, in _take_next_step
    [
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\agents\agent.py", line 1097, in <listcomp>
    [
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\agents\agent.py", line 1182, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain\agents\agent.py", line 1204, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain_core\tools.py", line 419, in run
    raise e
  File "C:\Users\combspk\.conda\envs\codeathon3\Lib\site-packages\langchain_core\tools.py", line 378, in run
    else self._run(*tool_args, **tool_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\Desktop\codeathon\mlxai-2024-team-saddler\app\agents\tp_tools\search.py", line 88, in _run
    return scholar2result_llm(self.llm, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\Desktop\codeathon\mlxai-2024-team-saddler\app\agents\tp_tools\search.py", line 59, in scholar2result_llm
    papers = paper_search(llm, query)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\Desktop\codeathon\mlxai-2024-team-saddler\app\agents\tp_tools\search.py", line 42, in paper_search
    papers = paper_scraper(search, pdir=str(Path("query") / f'{search_id}_{search_name}'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\combspk\Desktop\codeathon\mlxai-2024-team-saddler\app\agents\tp_tools\search.py", line 17, in paper_scraper
    return paperscraper.search_papers(search, pdir=pdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'paperscraper' has no attribute 'search_papers'
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete

**Comment by combspk** [comment]
We will also need to update the requirements.txt file with these new dependencies.

**Comment by combspk** [comment]
Ah, hold on - I think I'm using the wrong "paperscraper" package: it appears this is what you are using: https://github.com/blackadad/paper-scraper

**Comment by vestalisvirginis** [comment]
I think you got confused the same way I was.
There are 2 different paperscraper.
The original (understand the one use by CheCrow) is the following: https://github.com/blackadad/paper-scraper
For installing, check the Dockerfile in the last PR (the one waiting for validation) : pip install git+https://github.com/blackadad/paper-scraper.git
The problem is that it uses git+. But if the pipeline is runing inside a container it should be fine.

**Comment by combspk** [comment]
Got it, okay, I think I have it working now. Thanks!
