### ISSUE TITLE
NameError: name 'SemanticSearch' is not defined

### ISSUE THREAD

**Issue by vestalisvirginis** [NCBI-Codeathons/mlxai-2024-team-saddler#29]
Traceback (most recent call last):
  File "/usr/src/mlxai-2024-team-saddler/app/llm-test.py", line 6, in <module>
    tpa = tp.ToxPipeAgent(model="gpt-4", api_version="2024-02-15-preview", temp=0.0, max_iterations=40)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/mlxai-2024-team-saddler/app/agents/toxpipe.py", line 44, in __init__
    self.tools = make_tools(self.llm, verbose=verbose)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/mlxai-2024-team-saddler/app/agents/tools.py", line 19, in make_tools
    SemanticSearch(),
    ^^^^^^^^^^^^^^
NameError: name 'SemanticSearch' is not defined

**Comment by boratyng** [comment]
This should be fixed by PR #28.
